create table if not exists public.leads (
id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
 name text not null,mobile text not null,email text,city text,insurance_type text not null,source text not null default 'homepage',blog_slug text,age integer,
family_type text,existing_policy text,requirement text,preferred_contact text,status text not null default 'New',notes text,next_followup_at timestamptz);
create table if not exists public.advisor_leads (
id bigint generated by default as identity primary key,created_at timestamptz not null default now(),
name text not null,mobile text not null,email text,city text,experience text,employment text,message text,
status text not null default 'New',notes text,next_followup_at timestamptz);
create table if not exists public.blogs (
id bigint generated by default as identity primary key,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
title text not null,slug text not null unique,category text not null,excerpt text,content text not null,cover_image text,seo_title text,meta_description text,keywords text,author text default 'Insurance Gyani',published boolean not null default false,published_at timestamptz);
alter table public.leads add column if not exists source text not null default 'homepage';
alter table public.leads add column if not exists blog_slug text;
alter table public.leads enable row level security; alter table public.advisor_leads enable row level security; alter table public.blogs enable row level security;
drop policy if exists "public can insert insurance leads" on public.leads;
drop policy if exists "public can insert advisor leads" on public.advisor_leads;
drop policy if exists "public can read published blogs" on public.blogs;
drop policy if exists "admins can manage blogs" on public.blogs;
create policy "public can insert insurance leads" on public.leads for insert to anon,authenticated with check (true);
create policy "public can insert advisor leads" on public.advisor_leads for insert to anon,authenticated with check (true);
create policy "public can read published blogs" on public.blogs for select to anon,authenticated using (published=true);
create policy "admins can manage blogs" on public.blogs for all to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
-- Do not create public SELECT policies for leads or advisor_leads. View them through a protected admin/server API.

-- Seed only when the blog table is empty. Remove or edit these examples after adding your own articles.
do $$
begin
  if not exists (select 1 from public.blogs limit 1) then
    insert into public.blogs (title,slug,category,excerpt,content,seo_title,meta_description,keywords,published,published_at) values
    ('How Does Health Insurance Work?','how-does-health-insurance-work','Health Insurance','A practical introduction to hospitalisation cover, policy terms and the questions worth asking.','Health insurance generally helps cover eligible medical expenses according to the policy terms. Start by understanding who needs cover, the sum insured, waiting periods, exclusions and the claim process.\n\nBenefits, limits and eligibility differ by policy. Review the policy wording and ask the insurer for the official details before making a decision.','How Does Health Insurance Work? | Insurance Gyani','Understand the basics of health insurance, including cover, waiting periods, exclusions and claims.','health insurance,insurance basics',true,now()),
    ('What Is a Waiting Period in Health Insurance?','what-is-a-waiting-period-in-health-insurance','Health Insurance','Learn why some health insurance benefits may not be available immediately after purchase.','A waiting period is a defined time during which certain conditions or benefits may not be covered. The duration and situations covered by a waiting period depend on the policy wording.\n\nCheck the initial, specific-disease and pre-existing-condition waiting periods before choosing a policy. Ask the insurer how the rules apply to your situation.','What Is a Waiting Period in Health Insurance? | Insurance Gyani','A clear explanation of waiting periods in health insurance and what to check in your policy.','waiting period,health insurance',true,now()),
    ('Cashless vs Reimbursement Health Insurance Claims','cashless-vs-reimbursement-health-insurance-claims','Claims','Understand the general difference between cashless and reimbursement claim processes.','A cashless request generally involves a network hospital coordinating pre-authorisation with the insurer or TPA. A reimbursement request generally means you pay eligible expenses first and submit documents for review.\n\nBoth processes depend on the policy, documents and the insurer’s assessment. Always check the official process and timelines for your policy.','Cashless vs Reimbursement Health Insurance Claims | Insurance Gyani','Compare the general cashless and reimbursement claim processes for health insurance.','cashless claim,reimbursement claim',true,now()),
    ('What Is Term Insurance?','what-is-term-insurance','Life Insurance','Understand the role of term insurance in long-term family protection planning.','Term insurance generally provides life protection for a defined policy term. If the insured person dies during the term, the applicable benefit may be payable to the nominee, subject to the policy terms.\n\nConsider the protection need, term, exclusions, premium affordability and nominee details. Product terms and eligibility vary by insurer.','What Is Term Insurance? | Insurance Gyani','Learn what term insurance generally covers and what to review before choosing a policy.','term insurance,life insurance',true,now()),
    ('What Does Motor Insurance Generally Cover?','what-does-motor-insurance-generally-cover','Motor Insurance','A simple guide to third-party liability, own damage, IDV and common policy considerations.','Motor insurance generally includes third-party liability cover and may include own-damage protection depending on the policy. The insured declared value, deductibles, exclusions and add-ons affect the cover.\n\nRead the schedule and policy wording, follow notification timelines and ask the insurer what documents are required after an incident.','What Does Motor Insurance Generally Cover? | Insurance Gyani','Understand common motor insurance cover terms including third party, own damage and IDV.','motor insurance,car insurance,bike insurance',true,now()),
    ('Things to Check Before Buying Health Insurance','things-to-check-before-buying-health-insurance','Insurance Tips','A practical checklist for comparing health insurance beyond the premium.','Before buying health insurance, consider who needs cover, the sum insured, room-rent limits, waiting periods, exclusions, network hospitals, restoration rules and the claim process.\n\nCompare the policy wording and ask questions about situations that matter to your family. The lowest premium is not always the best fit for every requirement.','Things to Check Before Buying Health Insurance | Insurance Gyani','Use this practical checklist when reviewing health insurance options for your family.','health insurance,insurance tips',true,now());
  end if;
end $$;
