create table if not exists public.leads (
id bigint generated by default as identity primary key,
created_at timestamptz not null default now(),
name text not null,mobile text not null,email text,city text,
insurance_type text not null,age integer,family_type text,existing_policy text,
requirement text,preferred_contact text,status text not null default 'New',
notes text,next_followup_at timestamptz
);
create table if not exists public.blogs (
id bigint generated by default as identity primary key,
created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
title text not null,slug text not null unique,category text not null,excerpt text,
content text not null,cover_image text,seo_title text,meta_description text,keywords text,
author text default 'Insurance Gyani',published boolean not null default false,published_at timestamptz
);
alter table public.leads enable row level security;
alter table public.blogs enable row level security;
create policy "public can insert leads" on public.leads for insert to anon,authenticated with check (true);
create policy "public can read published blogs" on public.blogs for select to anon,authenticated using (published=true);
-- Never create a public SELECT policy on leads. Use a protected server/admin API.
