import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Routes,Route,Link,useParams}from'react-router-dom';
import{ShieldCheck,HeartPulse,CarFront,Users,ArrowRight,Phone,MessageCircle,CheckCircle2,Menu,X,BookOpen,Mail,ChevronDown,LockKeyhole}from'lucide-react';
import{supabase}from'./supabase';
import'./styles.css';

const phone=import.meta.env.VITE_PHONE||'+919999999999',wa=(import.meta.env.VITE_WHATSAPP||'919999999999').replace(/\D/g,''),email=import.meta.env.VITE_EMAIL||'hello@insurancegyani.in';
const products=[
['Health Insurance','/health-insurance',HeartPulse,'Individual, family, senior citizen, maternity, critical illness and top-up guidance.'],
['Life Insurance','/life-insurance',ShieldCheck,'Understand term and life protection options for your family.'],
['Motor Insurance','/motor-insurance',CarFront,'Car and two-wheeler insurance guidance, renewal and coverage assistance.'],
['Other Insurance','/other-insurance',Users,'Travel, personal accident and other protection requirements.']
];

function Header({quote}){const[o,setO]=useState(false);return <header><div className="container nav"><Link className="brand" to="/"><i><ShieldCheck/></i><b>Insurance<span>GYANI</span></b></Link><button className="mobile" onClick={()=>setO(!o)}>{o?<X/>:<Menu/>}</button><nav className={o?'open':''}><Link to="/">Home</Link><Link to="/health-insurance">Health</Link><Link to="/life-insurance">Life</Link><Link to="/motor-insurance">Motor</Link><Link to="/blogs">Blogs</Link><Link to="/faqs">FAQs</Link><Link to="/contact">Contact</Link></nav><button className="btn primary top" onClick={quote}>Get Free Quote</button></div></header>}

function Lead({close}){const[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[f,setF]=useState({name:'',mobile:'',email:'',city:'',insurance_type:'Health Insurance',age:'',family_type:'Individual',existing_policy:'No',requirement:'',preferred_contact:'Phone',consent:false});const set=(k,v)=>setF({...f,[k]:v});async function submit(e){e.preventDefault();if(!f.consent)return alert('Please accept the consent.');setBusy(true);try{if(!supabase)throw Error('Database not configured');const{error}=await supabase.from('leads').insert([{...f,age:f.age?Number(f.age):null}]);if(error)throw error;setSent(true)}catch(e){console.error(e);alert('Unable to submit right now. Please call us directly.')}finally{setBusy(false)}}return <div className="back"><div className="modal"><button className="close" onClick={close}><X/></button>{sent?<div className="success"><CheckCircle2 size={55}/><h2>Requirement received</h2><p>Thank you. Our team will contact you using the details provided.</p><button className="btn primary" onClick={close}>Done</button></div>:<><small>FREE INSURANCE ASSISTANCE</small><h2>Tell us what you need</h2><p className="muted">Share a few details and we'll get in touch.</p><form onSubmit={submit}><input required placeholder="Full name" value={f.name} onChange={e=>set('name',e.target.value)}/><input required pattern="[0-9]{10}" placeholder="10-digit mobile" value={f.mobile} onChange={e=>set('mobile',e.target.value.replace(/\D/g,'').slice(0,10))}/><input type="email" placeholder="Email" value={f.email} onChange={e=>set('email',e.target.value)}/><input placeholder="City" value={f.city} onChange={e=>set('city',e.target.value)}/><select value={f.insurance_type} onChange={e=>set('insurance_type',e.target.value)}>{['Health Insurance','Life Insurance','Motor Insurance','Travel Insurance','Personal Accident','Other'].map(x=><option>{x}</option>)}</select><input type="number" min="1" max="120" placeholder="Age" value={f.age} onChange={e=>set('age',e.target.value)}/><select value={f.family_type} onChange={e=>set('family_type',e.target.value)}><option>Individual</option><option>Family</option></select><select value={f.existing_policy} onChange={e=>set('existing_policy',e.target.value)}><option>No</option><option>Yes</option></select><select value={f.preferred_contact} onChange={e=>set('preferred_contact',e.target.value)}><option>Phone</option><option>WhatsApp</option><option>Email</option></select><textarea placeholder="Your requirement" value={f.requirement} onChange={e=>set('requirement',e.target.value)}/><label><input type="checkbox" checked={f.consent} onChange={e=>set('consent',e.target.checked)}/> I agree to be contacted regarding my insurance requirement.</label><button disabled={busy} className="btn primary full">{busy?'Submitting...':'Submit Requirement'} <ArrowRight/></button></form></>}</div></div>}

function Footer(){return <footer><div className="container foot"><Link className="brand" to="/"><i><ShieldCheck/></i><b>Insurance<span>GYANI</span></b></Link><p>Compare. Understand. Choose with confidence.</p><div><Link to="/blogs">Blogs</Link> <Link to="/faqs">FAQs</Link> <Link to="/privacy-policy">Privacy</Link> <Link to="/disclaimer">Disclaimer</Link></div></div></footer>}

function Layout({children,quote}){return <><Header quote={quote}/>{children}<div className="float"><a href={'tel:'+phone}><Phone/></a><a href={'https://wa.me/'+wa} target="_blank"><MessageCircle/></a></div><Footer/></>}

function Home({quote}){return <><section className="hero"><div className="container heroGrid"><div><small>PERSONALISED INSURANCE GUIDANCE</small><h1>Insurance made simple.<br/><em>Protection made smarter.</em></h1><p>Understand your insurance options, compare what matters and choose coverage with confidence.</p><div className="actions"><button className="btn primary" onClick={quote}>Get Free Quote <ArrowRight/></button><a className="btn secondary" href={'tel:'+phone}><Phone/> Talk to an Expert</a></div><div className="trust"><CheckCircle2/> Clear guidance <CheckCircle2/> Easy process <CheckCircle2/> Continued support</div></div><div className="visual"><div><div className="shield"><ShieldCheck size={70}/></div><h3>Your protection, your choice.</h3><p>Get help understanding coverage, exclusions and policy terms before you decide.</p></div><aside><HeartPulse/> <b>Health</b><span>Protection</span></aside><aside><CarFront/><b>Motor</b><span>Assistance</span></aside></div></div></section><section className="section"><div className="container"><small>INSURANCE SOLUTIONS</small><h2>Protection for the things that matter.</h2><div className="grid">{products.map(([t,path,I,text])=><article><div className="icon"><I/></div><h3>{t}</h3><p>{text}</p><Link to={path}>Explore <ArrowRight/></Link></article>)}</div></div></section><section className="soft"><div className="container split"><div><small>WHY INSURANCE GYANI</small><h2>Advice that starts with understanding.</h2><p>Insurance can feel complicated. We make the important parts easier to understand so you can make an informed decision.</p><ul>{['Understand coverage and key exclusions','Explore options suited to your requirement','Get assistance through the buying process','Receive ongoing renewal and service support'].map(x=><li><CheckCircle2/>{x}</li>)}</ul></div><div className="steps">{['Tell us your requirement','Get personalised guidance','Choose with confidence'].map((x,i)=><div><b>0{i+1}</b><h3>{x}</h3><p>{['Share a few details through our secure lead form.','Discuss relevant insurance options with you.','Understand the terms before moving ahead.'][i]}</p></div>)}</div></div></section><BlogsPreview/><CTA quote={quote}/></>}

function BlogsPreview(){const[p,setP]=useState([]);useEffect(()=>{supabase?.from('blogs').select('*').eq('published',true).order('published_at',{ascending:false}).limit(3).then(({data})=>setP(data||[]))},[]);const a=p.length?p:[{title:'How to choose health insurance for your family',category:'Health Insurance',excerpt:'Key things to look at before choosing a family health insurance plan.'},{title:'Health insurance waiting period explained',category:'Health Insurance',excerpt:'A simple guide to common waiting periods and why they matter.'},{title:'Term insurance: what should you know?',category:'Life Insurance',excerpt:'Understand the basics of term insurance and financial protection.'}];return <section className="section"><div className="container"><small>INSURANCE KNOWLEDGE</small><h2>From the Insurance Gyani blog.</h2><div className="blogs">{a.map(b=><article><div className="blogimg"><BookOpen/></div><div><small>{b.category}</small><h3>{b.title}</h3><p>{b.excerpt}</p>{b.slug&&<Link to={'/blog/'+b.slug}>Read article <ArrowRight/></Link>}</div></article>)}</div></div></section>}

function CTA({quote}){return <section className="cta"><div className="container"><div><small>NEED HELP?</small><h2>Not sure which insurance you need?</h2><p>Tell us your requirement. We'll help you understand your options.</p></div><button className="btn white" onClick={quote}>Get Free Quote <ArrowRight/></button></div></section>}

function Product({type,quote}){const d={Health:['Health Insurance',['Individual Health Insurance','Family Health Insurance','Senior Citizen Health Insurance','Maternity Insurance','Critical Illness Insurance','Top-up & Super Top-up','Personal Accident Insurance','Health Insurance Portability']],Life:['Life Insurance',['Term Insurance','Life Protection','Family Financial Protection','Long-term Protection']],Motor:['Motor Insurance',['Car Insurance','Two-Wheeler Insurance','Comprehensive Insurance','Third Party Insurance','Motor Renewal']],Other:['Other Insurance',['Travel Insurance','Personal Accident Insurance','Other Protection Requirements']]}[type];return <><section className="inner"><div className="container"><small>INSURANCE</small><h1>{d[0]}</h1><p>Understand your options before you choose.</p><button className="btn primary" onClick={quote}>Get Free Quote <ArrowRight/></button></div></section><section className="section"><div className="container narrow"><h2>What you can explore</h2><ul className="explore">{d[1].map(x=><li><CheckCircle2/>{x}</li>)}</ul><div className="info"><h3>Make an informed decision</h3><p>Coverage, exclusions, waiting periods, eligibility and underwriting can vary by insurer and product. Always review the policy wording.</p><button className="btn primary" onClick={quote}>Discuss Your Requirement</button></div></div></section></>}

function FAQs(){const qs=['How do I choose the right health insurance?','What is a waiting period?','What is a family floater?','Can I port my health insurance policy?','What is term insurance?','What is comprehensive motor insurance?','Can I get help after buying a policy?'];return <section className="section narrow"><small>FAQS</small><h1>Frequently asked questions</h1>{qs.map(q=><details><summary>{q}<ChevronDown/></summary><p>The answer depends on your needs and the policy terms. Always review coverage, exclusions, waiting periods, eligibility and insurer-specific conditions before making a decision.</p></details>)}</section>}

function Contact({quote}){return <section className="contact"><div className="container split"><div><small>CONTACT INSURANCE GYANI</small><h1>Let's talk about your requirement.</h1><p>Need help with health, life, motor or other insurance? Get in touch with our team.</p><div className="contacts"><a href={'tel:'+phone}><Phone/><span><b>Call us</b>{phone}</span></a><a href={'mailto:'+email}><Mail/><span><b>Email</b>{email}</span></a><a href={'https://wa.me/'+wa} target="_blank"><MessageCircle/><span><b>WhatsApp</b>Chat with us</span></a></div></div><div className="card"><LockKeyhole/><h3>Your information stays private.</h3><p>We use submitted details only to respond to your insurance requirement. Do not share sensitive financial or identity documents through the form.</p><button className="btn primary full" onClick={quote}>Start Your Requirement</button></div></div></section>}

function Blogs(){const[p,setP]=useState([]);useEffect(()=>{supabase?.from('blogs').select('*').eq('published',true).order('published_at',{ascending:false}).then(({data})=>setP(data||[]))},[]);return <section className="section"><div className="container"><small>INSURANCE KNOWLEDGE</small><h1>Insurance Gyani Blog</h1><p className="lead">Simple explanations and practical insurance education.</p><div className="blogs">{p.map(b=><article><div className="blogimg"><BookOpen/></div><div><small>{b.category}</small><h3>{b.title}</h3><p>{b.excerpt}</p><Link to={'/blog/'+b.slug}>Read article <ArrowRight/></Link></div></article>)}</div>{!p.length&&<p>New articles coming soon.</p>}</div></section>}

function Post(){const{slug}=useParams(),[p,setP]=useState(null);useEffect(()=>{supabase?.from('blogs').select('*').eq('slug',slug).eq('published',true).single().then(({data})=>setP(data))},[slug]);if(!p)return <section className="section narrow"><h1>Article not found</h1><Link className="btn secondary" to="/blogs">Back to Blogs</Link></section>;return <section className="section"><div className="container article"><small>{p.category}</small><h1>{p.title}</h1><p className="lead">{p.excerpt}</p>{p.content.split('\n').map(x=><p>{x}</p>)}</div></section>}

function Legal({title}){return <section className="section narrow"><small>INSURANCE GYANI</small><h1>{title}</h1><p>Insurance information on this website is educational and for general guidance. Product availability, benefits, exclusions, eligibility, underwriting and policy terms are subject to the respective insurer and policy wording.</p><h3>Website use</h3><p>Please use this website responsibly and do not submit sensitive identity or financial documents through the public lead form.</p></section>}

function App(){const[show,setShow]=useState(false),quote=()=>setShow(true);return <Layout quote={quote}><Routes><Route path="/" element={<Home quote={quote}/>}/><Route path="/health-insurance" element={<Product type="Health" quote={quote}/>}/><Route path="/life-insurance" element={<Product type="Life" quote={quote}/>}/><Route path="/motor-insurance" element={<Product type="Motor" quote={quote}/>}/><Route path="/other-insurance" element={<Product type="Other" quote={quote}/>}/><Route path="/blogs" element={<Blogs/>}/><Route path="/blog/:slug" element={<Post/>}/><Route path="/faqs" element={<FAQs/>}/><Route path="/contact" element={<Contact quote={quote}/>}/><Route path="/privacy-policy" element={<Legal title="Privacy Policy"/>}/><Route path="/terms" element={<Legal title="Terms & Conditions"/>}/><Route path="/disclaimer" element={<Legal title="Disclaimer"/>}/></Routes>{show&&<Lead close={()=>setShow(false)}/>}</Layout>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
